# Flask
from flask import jsonify

# Models
from project.models import Account
from project.accounts.accounts import create_account, generate_unique_iban


def api_create_account(account):

    # Title validation (existence, length, type) and error messages are automatically generated by swagger!
    title = account.get('title')
    if not title:
        return jsonify({"status": "error", "message": "This was unexpected. Swagger should have handled this..."}), 400

    new_iban = generate_unique_iban()

    status, message = create_account(new_iban, title) # Validates request data internally (given it is not None)

    if status == "success":
        account = Account.query.filter(Account.iban == new_iban).first()
        return jsonify({
                "status": "success",
                "detail": message,
                "iban": account.iban,
                "title": account.title,
                "id": account.id
            }), 201
    else:
        return jsonify({"status": "error", "detail": message}), 400
