# Flask
from flask import jsonify

from datetime import datetime
from flask import request

# Models
from project.models import Transaction, Account
from project.transactions.transactions import create_transaction

import re
import pytz

def api_create_transaction(account_id):
    # Validate accounts exists
    account = Account.query.get(account_id)
    if not account:
        return jsonify({"status": "error", "detail": "Account not found"}), 400

    # Validate required parameters are present
    data = request.get_json()
    required_fields = ["description", "amount", "category"] # Description, account_id, amount, category validation and error messages are automatically generated by swagger!
    for field in required_fields:
        if data.get(field) is None:
            return jsonify({"status": "error", "detail": "This was unexpected. Swagger should have handled this..."}), 400

    utc_datetime_booked = None
    if data.get("utc_datetime_booked") != None:

        # Validate format of date_time (roughly to indicate to user what went wrong. All other errors will return generic error message)
        datetime_string = data.get("utc_datetime_booked")
        pattern = re.compile(r'^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z$')
        match = pattern.match(datetime_string)

        if not match:
            return jsonify({"status": "error", "detail": "utc_datetime_booked was not provided in the correct format."}), 400
        try:
            utc_datetime_booked_string = datetime.fromisoformat(data.get("utc_datetime_booked").replace('Z', '+00:00'))
            utc_datetime_booked = utc_datetime_booked_string.replace(tzinfo=pytz.UTC)
        except:
            return jsonify({"status": "error", "detail": "Could not convert utc_datetime_booked to datetime object"}), 400

    status, message, transaction_id = create_transaction(account=account,
                                        description=data.get("description"),
                                        amount=data.get("amount"),
                                        category=data.get("category"),
                                        utc_datetime_booked=utc_datetime_booked
                                        )

    if status == "success":
        transaction = Transaction.query.get(transaction_id)
        return jsonify({
        "status": "success",
        "detail": "Successfully created new transaction.",
        "description": transaction.description,
        "amount": transaction.amount,
        "saldo": transaction.saldo,
        "transaction_id": transaction.id,
        "category": transaction.category,
        "utc_datetime_booked": transaction.utc_datetime_booked
    }), 201

    else:
        return jsonify({"status": "error", "detail": message}), 400




# # ## API endpoints
# def transactions_to_json(transaction_list):
#     json_transactions = []
#     for transaction in transaction_list:
#         transaction_dict = {
#             "id": str(transaction.id),
#             "amount": str(transaction.amount),
#             "saldo": str(transaction.saldo),
#             "description": transaction.description,
#             "category": transaction.category,
#             "utc_datetime_booked": transaction.utc_datetime_booked.isoformat()
#         }
#         json_transactions.append(transaction_dict)
#     return json_transactions

# # Read all transactions
# def read_all():
#     return transactions_to_json(Transaction.query.all())

# # Read single transaction
# def read_one(id):
#     data = Transaction.query.get(id)
#     if data:
#         return transactions_to_json([data])
#     else:
#         abort(
#             404, f"Transaction with id {id} not found"
#         )
